#Problem 2: Even Fibonacci Numbers
#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first ten terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#find the sum of the even-valued terms.
def even_fibonacci_sum(limit):
    a, b = 1, 2  # Starting Fibonacci numbers
    total = 0    # To store the sum of even Fibonacci numbers

    while b <= limit:
        if b % 2 == 0:     # Check if the number is even
            total += b     # Add even Fibonacci number to total
        a, b = b, a + b     # Move to the next Fibonacci number

    return total

# Run the function with a limit of 4 million
print(even_fibonacci_sum(4000000))

